### ISSUE TITLE
Error: 413 (Payload Too Large)

### ISSUE THREAD

**Issue by daniel-zahariev** [alex-milanov/mongo-admin#1]
Got an error `413 (Payload Too Large)` when i tried to create a document with the contents of the attached JSON file.

[electroNow.json.zip](https://github.com/alex-milanov/mongo-admin/files/516278/electroNow.json.zip)

**Comment by alex-milanov** [comment]
ok. I will check it. Thanks for reporting. :-)

**Comment by alex-milanov** [comment]
Fixed. Now you should be able to upload JSON's up to 50mb.
